version: 2
project_name: viewnode

before:
  hooks:
    - go mod tidy

builds:
  - id: viewnode
    main: ./main.go
    binary: viewnode
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: artifacts
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs(\\(.+\\))?:"
      - "^test(\\(.+\\))?:"
      - "^chore(\\(.+\\))?:"
