apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: viewnode
spec:
  version: {{ .TagName }}
  homepage: https://github.com/NTTDATA-DACH/viewnode
  shortDescription: Displays nodes with their pods and containers and provides metrics for resources
  description: |
    This plugin displays nodes with their pods and containers.
    It provides information about requested and used resources, e.g. memory.
    It supports filtering of nodes and pods.
    It is very useful when you need to monitor multiple resources like nodes, pods or containers
    in a dynamic environment like a CI/CD platform where pods live and die frequently.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/NTTDATA-DACH/viewnode/releases/download/{{ .TagName }}/viewnode_{{ .TagName }}_darwin_amd64.tar.gz" .TagName | indent 6 }}
      bin: viewnode
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/NTTDATA-DACH/viewnode/releases/download/{{ .TagName }}/viewnode_{{ .TagName }}_darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: viewnode
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/NTTDATA-DACH/viewnode/releases/download/{{ .TagName }}/viewnode_{{ .TagName }}_linux_amd64.tar.gz" .TagName | indent 6 }}
      bin: viewnode
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/NTTDATA-DACH/viewnode/releases/download/{{ .TagName }}/viewnode_{{ .TagName }}_windows_amd64.tar.gz" .TagName | indent 6 }}
      bin: viewnode.exe