apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: viewnode
spec:
  version: v0.8.1
  homepage: https://github.com/NTTDATA-DACH/viewnode
  shortDescription: Displays nodes with their pods and containers and provides metrics for resources
  description: |
    This plugin displays nodes with their pods and containers.
    It provides information about requested and used resources, e.g. memory.
    It supports filtering of nodes and pods.
    It is very useful when you need to monitor multiple resources like nodes, pods or containers
    in a dynamic environment like a CI/CD platform where pods live and die frequently.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.1/viewnode_0.8.1_darwin_amd64.tar.gz
      sha256: 1e4e2c0dacd0833e56e245643e03fa0fc1fc4b3337f53e4fdf18d218a66b5f16
      bin: viewnode
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.1/viewnode_0.8.1_linux_amd64.tar.gz
      sha256: 5ae5c23cab293938c9eae429d35a3e4dfab1971ffaaeaa4ce3e3a05ba1949333
      bin: viewnode
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.1/viewnode_0.8.1_windows_amd64.tar.gz
      sha256: 8a123f547275e8522bdb8eb8c7d9ca73a5a3a886c59993839da13ef4d31f8d4b
      bin: viewnode.exe
