apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: viewnode
spec:
  version: v0.8.0-alpha
  homepage: https://github.com/NTTDATA-DACH/viewnode
  shortDescription: Displays nodes with their pods and containers and provides metrics for resources
  description: |
    This plugin displays nodes with their pods and containers.
    It provides information about requested and used resources, e.g. memory.
    It supports filtering of nodes and pods.
    It is very useful when you need to monitor multiple resources like nodes, pods or containers
    in a dynamic environment like a CI/CD platform where pods live and die frequently.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0/viewnode_v0.8.0-next_darwin_amd64.tar.gz
      sha256: 60335d96dc764056272f73a0e28398bca43489f90e0d0e3455ec2b11bebd71dd
      bin: viewnode
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0/viewnode_v0.8.0-next_linux_amd64.tar.gz
      sha256: 852e135e5387df5aaf2842db8808986f0f05a7d1d1c72f68a7ab0441d0a1d6fe
      bin: viewnode
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0/viewnode_v0.8.0-next_windows_amd64.tar.gz
      sha256: 48307d9717a3b7239baf246284b5e9af319a26eab01f0a5351de3254745f8bd0
      bin: viewnode.exe
