apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: viewnode
spec:
  version: v0.8.0-alpha
  homepage: https://github.com/NTTDATA-DACH/viewnode
  shortDescription: Displays nodes with their pods and containers and provides metrics for resources
  description: |
    This plugin displays nodes with their pods and containers.
    It provides information about requested and used resources, e.g. memory.
    It supports filtering of nodes and pods.
    It is very useful when you need to monitor multiple resources like nodes, pods or containers
    in a dynamic environment like a CI/CD platform where pods live and die frequently.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0-alpha/viewnode_0.8.0-alpha_darwin_amd64.tar.gz
      sha256: f6de499fbc076b0109f2c1cb4ca2b78707a6ef6c1a3d0b430236ea4a0394e74d
      bin: viewnode
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0-alpha/viewnode_0.8.0-alpha_linux_amd64.tar.gz
      sha256: ff43734fecd8422f2c0b83c49bf660bbb4c1b7a97d657f76ba9b2c7666854e51
      bin: viewnode
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/NTTDATA-DACH/viewnode/releases/download/v0.8.0-alpha/viewnode_0.8.0-alpha_windows_amd64.tar.gz
      sha256: 3140911b954a61b81d728564c9a00929388ed43c68e3b31c43324964284a9f0d
      bin: viewnode.exe
