name: Build and Test
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: make build
      - name: Run Unit Tests with Coverage
        run: make test
      - name: Upload Coverage
        uses: codecov/codecov-action@v3