name: Update Krew Index

on:
  workflow_run:
    workflows:
      - Release Binaries
    types:
      - completed

permissions:
  contents: write

jobs:
  update-krew-index:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.47
